# Introducing Libraries: NumPy

![libgif](https://media0.giphy.com/media/7E8lI6TkLrvvAcPXso/giphy.gif?cid=790b76115d360a95792e4333770609b8&rid=giphy.gif)

## Introduction

#### _Our goals today are to be able to_: <br/>

- Identify and import Python modules and packages (libraries)
- Identify differences between NumPy and base Python in usage and operation
- Create a new module of our own

#### _Big questions for this lesson_: <br/>
- What is a package, what do packages do, and why might we want to use them?
- When do we want to use NumPy?

### Activation:

![excel2](img/excelpic2.jpg)

Most people have used Microsoft Excel or Google sheets. But what are the limitations of excel?

- [Take a minute to read this article](https://www.bbc.com/news/magazine-22223190)
- make a list of problems excel presents

How is using python different?

Python
- create documentation of processes as you code
- reduces chances for human error
- do "drag and drop"
- repeatable
- transparent

## 1. Importing Python packages 


In an earlier lesson, we wrote a function to calculate the mean of an list. That was **tedious**. To make our code efficient we could store that function in a *python module* and call it later when we need it. 

And thankfully, other people have _also_ wrote and optimized functions and wrapped them into **modules** and **packages** (also known as _libraries_ )


### Terminology

![mod2](img/modules2.png)

### Terminology

![packages3](img/packages3.png)

![python-fact](img/python_def.png)

### pip & the Python Package Index

![pypi](img/pypi_packages.png)

### You're not limited to PyPI

Make your own modules
![pipmod](img/import_modules.png)

![pippack](img/package_redo.png)

### First library we will import is `Numpy`


![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 


To import a package type `import` followed by the name of the package as shown below.

In [ ]:
import numpy # Look, ma! we're importing!

#### Alias libraries

Many packages have a canonical way to import them with an abbreviated alias.

In [ ]:
import numpy as np # np = alias

#### Other standard aliases 

In [ ]:
import scipy
import pandas as pd
import matplotlib as mpl
import statsmodels as sm

### Import specific modules from a larger package

In [ ]:
# sometimes we will want to import a specific module from a package
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt 

#### Helpful links: package documentation

Packages have associated documentation to explain how to use the different tools included in a package.

_Sample of libraries_
- [NumPy](https://docs.scipy.org/doc/numpy/)
- [SciPy](https://docs.scipy.org/doc/scipy/reference/)
- [Pandas](http://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/contents.html)

## 2. NumPy versus base Python

Now that we know packages exist, why do we want to use them? Let us examine a comparison between base Python and Numpy.

Python has lists and normal python can do basic math. NumPy, however, has the helpful objects called **arrays**.

Numpy has a few advantages over base Python which we will look at.

In [ ]:
l = [1,2,3]
x=numpy.array([1,2,3])
print(x)


y=np.array([4,5,6])
print(y)

#### New type of object

In [ ]:
type(x)

### Numpy makes math easy

Because of numpy we can now get the **mean** and other quick math of lists and arrays.

In [ ]:
example = [4,3,25,40,62,20]
print(np.mean(example))

#### Different types of arrays

In [ ]:
names_list=['Bob','John','Sally']
names_array=numpy.char.array(['Bob','John','Sally']) #use numpy.array for numbers and numpy.char.array for strings
print(names_list)
print(names_array)

#### Array math in action

In [ ]:
# Make a list and an array of three numbers

#your code here
numbers_list = [5,22,33,90]
numbers_array = np.array([5,22,33,90])

In [ ]:
# divide your array by 2

numbers_array/2

In [ ]:
# divide your list by 2

numbers_list/2

Numpy arrays support the `div()` operator while python lists do not. There are other things that make it useful to utilize numpy over base python for evaluating data.

In [ ]:
# shape tells us the size of the array

numbers_array.shape

### Numpy array and matrix creation functions

Take 5 minutes and explore each of the following functions.  What does each one do?  What is the syntax of each?
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eye()`
- `np.random.random()`

In [ ]:
np.zeros(5)

In [ ]:
np.ones(5)

In [ ]:
np.full((3,3),3.3)


In [ ]:
np.eye(6)

In [ ]:
np.random.random(6)

### Slicing in NumPy

In [ ]:
# Selection and assignment work as you might expect
numbers_array[1]

In [ ]:
numbers_array[1] = 10
numbers_array

In [ ]:
# We remember slicing from lists
numbers_list = list(range(10))
numbers_list[3:7]

In [ ]:
# Slicing in NumPy Arrays is very similar!
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
a.shape

In [ ]:
# first 2 rows, columns 1 & 2 (remember 0-index!)
b = a[:2, 1:3]
b

### Datatypes in NumPy

In [ ]:
a.dtype

In [ ]:
names_list.dtype

In [ ]:
a.astype(np.float64)

### More Array Math 
#### Adding matrices 

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)

In [ ]:
print(np.add(x, y))

#### Subtracting matrices 

In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)

In [ ]:
print(np.subtract(x, y))

#### Multiplying matrices 

In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)

In [ ]:
print(np.multiply(x, y))

#### Dividing matrices 

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

In [ ]:
print(np.divide(x, y))

#### Raising matrices to powers 

In [ ]:
# Elementwise square root; both produce the same array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(x ** (1/2))

In [ ]:
print(np.sqrt(x))

### Numpy is faster

Below, you will find a piece of code we will use to compare the speed of operations on a list and operations on an array. In this speed test, we will use the package [time](https://docs.python.org/3/library/time.html).

In [ ]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print("python: " + str(t1), "numpy: "+ str(t2))
print("Numpy is in this example " + str(t1/t2) + " times faster!")

In pairs, run the speed test with a different number, and share your results with the class.

## 3. Making our own module
![modlife](https://media1.giphy.com/media/dW0KhIROCaAdCO0V3S/giphy.gif?cid=790b76115d36096678416c65519d8082&rid=giphy.gif)

In [ ]:
# this option will re-import your module each time you save an update to it

%load_ext autoreload
%autoreload 2

In [ ]:
import temperizer as tp

## Example: Convert F to C

1. This function is already implemented in `temperizer.py`.
2. Notice that we can call the imported function and see the result.

In [ ]:
# 32F should equal 0C
tps.convert_f_to_c(32)

In [ ]:
# -40F should equal -40C
tps.convert_f_to_c(-40)

In [ ]:
# 212F should equal 100C
tps.convert_f_to_c(212)

## Your turn: Convert C to F

1. Find the stub function in `temperizer.py`
2. The word `pass` means "this space intentionally left blank."
3. Add your code _in place of_ the `pass` keyword, _below_ the docstring.
4. Run these cells and make sure that your code works.

In [ ]:
# 0C should equal 32F
tps.convert_c_to_f(0)

In [ ]:
# -40C should equal -40F
tps.convert_c_to_f(-40)

In [ ]:
# 100C should equal 212F
tps.convert_c_to_f(100)

## Next: Adding New Functions

You need to add support for Kelvin to the `temperizer` library.

1. Create new _stub functions_ in `temperizer.py`:

    * `convert_c_to_k`
    * `convert_f_to_k`
    * `convert_k_to_c`
    * `convert_k_to_f`

    Start each function with a docstring and the `pass` keyword, e.g.:

    ```
    def convert_f_to_k(temperature_f):
        """Convert Fahrenheit to Kelvin."""
        pass
    ```

2. Add cells to this notebook to test and validate these functions, similar to the ones above.

3. Then, go back to `temperizer.py` to replace `pass` with your code.

4. Run the notebook cells to make sure that your new functions work.

#### Small note:

Docstrings (those lines with `""" """` on either side) allow us to create self-documented code. 

Now later, if you forget what each function does, you can use the `?` or `help` functions the same way you would with other functions, and your documentation will show up!

In [ ]:
tps.convert_f_to_c()

### Extra credit:

make a function in your temperizer that will take a temp in F, and print out:

```
The temperature [number] F is:
    - x in C
    - y in k
```

In [ ]:
tps.convert_f_to_all(89)

## Congrats!!

You've now made your own module of temperature conversion functions!

#### _Our goals today were to be able to_: <br/>

- Identify and import Python modules and packages (libraries)
- Identify differences between NumPy and base Python in usage and operation
- Create a new module of our own

In [1]:
!pwd

/Users/apeeblesmadigan/Desktop/dc-ds-071519/1-Module/1-Section/day_4_lecture_1_libraries_numpy
